config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get ':language/words', to: redirect('/:language'), as: 'words'
  post ':language/words', to: 'words#index'
  get ':language', to: 'home#index', as: 'root'

  root 'home#index'
end

app/views/layouts/_header.html.erb
<header id="header" class="page-topbar">
  <div class="navbar-fixed">
    <nav class="navbar-color purple darken-4">
      <div class="nav-wrapper">

        <ul class="left">
          <li>
            <h1 class="logo-wrapper">
              <%= link_to 'Dictionary', root_path(@language), { class: 'brand-logo darken-1' } %>
            </h1>
          </li>
        </ul>

        <%= form_tag words_path do %>
          <div class="header-search-wrapper hide-on-med-and-down">
            <i class="material-icons">search</i>
            <input type="text" name="query" class="header-search-input z-depth-2"
              placeholder="Look up a word" id="search" value="<%= @word if @word %>">

            <div id="search-options">
              <input class="with-gap purple darken-4" name="search_type" type="radio"
                id="by-description" value="<%= SearchType::MEANING %>"
                <%= 'checked' if @search_type == SearchType::MEANING || !@search_type %>
              />
              <label for="by-description">Description</label>

              <input class="with-gap" name="search_type" type="radio"
                id="by-word" value="<%= SearchType::WORD %>"
                <%= 'checked' if @search_type == SearchType::WORD %>
              />
              <label for="by-word">Word</label>

              <input class="with-gap" name="search_type" type="radio"
                id="by-tag" value="<%= SearchType::TAG %>"
                <%= 'checked' if @search_type == SearchType::TAG %>
              />
              <label for="by-tag">Tag</label>
            </div>
          </div>
          <button class="btn dictionary-submit waves-effect waves-light hide-on-med-and-down" type="submit"
            name="action" id="search-button">Search</button>
        <% end %>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_loader.html.erb
<div id="loader-wrapper">
  <div id="loader"></div>
  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dictionary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body data-page="<%= pagejs %>">
    <%= render 'layouts/header' %>

    <section>
      <%= yield %>
    </section>

    <%= render 'layouts/loader' %>
  </body>
</html>